In [34]:
## TASK 1
import pandas as pd
url = "https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv"
df = pd.read_csv(url)

#calculate the total global sales for all games in the dataset
print("TASK 1 a\n")
total_sales = df["Global_Sales"].sum()
print(f"the total global sales of all games is {total_sales}")
#find the game with the highest global sales
print("TASK 1 b\n")
max_sales = df["Global_Sales"].max()
game_with_max_sales = df[df["Global_Sales"] == max_sales]
print(f"the game with the highest global sales is {game_with_max_sales['Name'].values[0]}")
#determine the average sales for each region
print("TASK 1 c\n")
average_sales = df[["NA_Sales","EU_Sales","JP_Sales","Other_Sales"]].mean()
print(f"the average sales for each region are\n{average_sales}")
#Find the top 5 most popular game genres based on global sales
print("TASK 1 d\n")
top_5_genres = df.groupby("Genre")["Global_Sales"].sum().sort_values(ascending=False).head(5)
print(f"the top 5 most popular game genres based on global sales are\n{top_5_genres}")
#Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
print("TASK 1 e\n")
total_sales_per_genre = df.groupby("Genre")[["NA_Sales","EU_Sales","JP_Sales","Other_Sales"]].sum()
most_popular_genre_in_NA = total_sales_per_genre["NA_Sales"].idxmax()
print(f"the most popular genre in North America is {most_popular_genre_in_NA}")
#Display the last 10 rows
print("TASK 1 f\n")
print(df.tail(10))
#Determine the top 3 gaming platforms with the highest global sales.
print("TASK 1 g\n")
top_3_platforms = df.groupby("Platform")["Global_Sales"].sum().sort_values(ascending=False).head(3)
print(f"the top 3 gaming platforms with the highest global sales are\n{top_3_platforms}")
#Calculate the market share (percentage of global sales) for each genre.
print("TASK 1 h\n")
market_share = df.groupby("Genre")["Global_Sales"].sum() / total_sales * 100
print(f"the market share for each genre is\n{market_share}")
#Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)
print("TASK 1 i\n")
correlation = df["NA_Sales"].corr(df["EU_Sales"])
print(f"the correlation coefficient between NA_Sales and EU_Sales is {correlation}")

TASK 1 a

the total global sales of all games is 8920.44
TASK 1 b

the game with the highest global sales is Wii Sports
TASK 1 c

the average sales for each region are
NA_Sales       0.264667
EU_Sales       0.146652
JP_Sales       0.077782
Other_Sales    0.048063
dtype: float64
TASK 1 d

the top 5 most popular game genres based on global sales are
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64
TASK 1 e

the most popular genre in North America is Action
TASK 1 f

        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                           

In [37]:
## TASK 2
english_spanish_dict = {
    "hello": "hola",
    "goodbye": "adiós",
    "please": "por favor",
    "thank you": "gracias",
    "yes": "sí",
    "no": "no",
    "cat": "gato",
    "dog": "perro",
    "house": "casa",
    "book": "libro",
}

while True:
    english_word = input("Enter an English word to translate (or type 'exit' to quit): ").strip().lower()
    
    if english_word == "exit":
        print("Thank you for using the dictionary. Goodbye!")
        break
    
    if english_word in english_spanish_dict:
        print(f"The Spanish translation for '{english_word}' is: {english_spanish_dict[english_word]}")
    else:
        print(f"Sorry, the translation for '{english_word}' is not available.")


Enter an English word to translate (or type 'exit' to quit):  book


The Spanish translation for 'book' is: libro


Enter an English word to translate (or type 'exit' to quit):  exit


Thank you for using the dictionary. Goodbye!


In [40]:
## TASK 3
def classify_emails(email_list):
    important_keywords = ["meeting", "urgent", "project", "deadline", "schedule"]
    promotion_keywords = ["sale", "discount", "offer", "deal", "promotion"]
    spam_keywords = ["win", "free", "lottery", "prize", "click here"]
    important_emails = []
    promotion_emails = []
    spam_emails = []
    for email in email_list:
        email_lower = email.lower()
        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)
        elif any(keyword in email_lower for keyword in promotion_keywords):
            promotion_emails.append(email)
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)

    return important_emails, promotion_emails, spam_emails
emails = [
    "meeting scheduled with FYP supervisor at 10AM",
    "SALE AT LEVIS: Get 2 jeans for the price of 1",
    "Win a FREE vacation to Hawaii! Click here for details",
    "Project update required by the end of the day",
    "Special Discount on your next purchase",
    "Claim your prize now! You've won a lottery",
    "Urgent: Deadline approaching for the quarterly report",
    "Promotion: Get 2 for the price of 1 this week",
]
important, promotions, spam = classify_emails(emails)
print("Important Emails:")
print("\n".join(important))
print("\nPromotions Emails:")
print("\n".join(promotions))
print("\nSpam Emails:")
print("\n".join(spam))


Important Emails:
meeting scheduled with FYP supervisor at 10AM
Project update required by the end of the day
Urgent: Deadline approaching for the quarterly report

Promotions Emails:
SALE AT LEVIS: Get 2 jeans for the price of 1
Special Discount on your next purchase
Promotion: Get 2 for the price of 1 this week

Spam Emails:
Win a FREE vacation to Hawaii! Click here for details
Claim your prize now! You've won a lottery


In [28]:
## TASK 4
shopping_cart = []

print("Welcome to the Tech Store!")
print("Available Products:")
print("1. AI Response Simulator - $199")
print("2. Investment Decision Tool - $299")
print("3. Quantum Computing API Access - $999")

while True:
    print("\nOptions:")
    print("1-3: Add product to cart")
    print("q: Checkout and exit")
    
    user_input = input("\nEnter your choice (1-3/q): ").strip().lower()
    
    if user_input == 'q':
        break
        
    try:
        choice = int(user_input)
        if 1 <= choice <= 3:
            products = [
                "AI Response Simulator",
                "Investment Decision Tool",
                "Quantum Computing API Access"
            ]
            selected_product = products[choice - 1]
            shopping_cart.append(selected_product)
            print(f"\n{selected_product} added to your cart!")
        else:
            print("\nPlease enter a number between 1 and 3")
    except ValueError:
        print("\nInvalid input. Please enter a number (1-3) or 'q' to checkout")

print("\nYour Shopping Cart:")
for index, item in enumerate(shopping_cart, 1):
    print(f"{index}. {item}")

print("\nThank you for shopping with us! Have a great day!")

Welcome to the Tech Store!
Available Products:
1. AI Response Simulator - $199
2. Investment Decision Tool - $299
3. Quantum Computing API Access - $999

Options:
1-3: Add product to cart
q: Checkout and exit



Enter your choice (1-3/q):  1



AI Response Simulator added to your cart!

Options:
1-3: Add product to cart
q: Checkout and exit



Enter your choice (1-3/q):  1



AI Response Simulator added to your cart!

Options:
1-3: Add product to cart
q: Checkout and exit



Enter your choice (1-3/q):  1



AI Response Simulator added to your cart!

Options:
1-3: Add product to cart
q: Checkout and exit



Enter your choice (1-3/q):  1



AI Response Simulator added to your cart!

Options:
1-3: Add product to cart
q: Checkout and exit



Enter your choice (1-3/q):  q



Your Shopping Cart:
1. AI Response Simulator
2. AI Response Simulator
3. AI Response Simulator
4. AI Response Simulator

Thank you for shopping with us! Have a great day!


In [22]:
## TASK 5
## 1 ADDITION
import numpy as np
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
addition = arr1 + arr2

print("Element-wise Addition:")
print(addition)

## 2 PRODUCT

import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

prodct = arr1 * arr2

print("\nElement-wise Product:")
print(prodct)


Element-wise Addition:
[[ 6  8]
 [10 12]]

Element-wise Product:
[[ 5 12]
 [21 32]]


In [11]:
## TASK 6
## 1 RESHAPUNG
import numpy as np

ONEDARRAY = np.arange(12)

TWODARRAY = ONEDARRAY.reshape(3, 4)

print("Reshaped 2D Array:")
print(TWODARRAY)

## 2 CONCATENATE
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

horizontally_concatenated = np.hstack((arr1, arr2))

vertically_concatenated = np.vstack((arr1, arr2))

print("Horizontally Concatenated Array:")
print(horizontally_concatenated)

print("\nVertically Concatenated Array:")
print(vertically_concatenated)


Reshaped 2D Array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Horizontally Concatenated Array:
[[1 2 5 6]
 [3 4 7 8]]

Vertically Concatenated Array:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [9]:
## TASK 7
l = [1, 2, 3, 4, 5]
reverse = l[::-1]
print(reverse)


[5, 4, 3, 2, 1]
